spring.application.name=fity
spring.datasource.url = jdbc:mysql://my-mysql:3306/fity?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= my-secret-pw
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto=update